### ISSUE TITLE
EPIC 5 (Commenting System)

### ISSUE THREAD

**Issue by Harmonica-Men** [Harmonica-Men/AstroShare-Blog#10]
**Description:** Implement a commenting system for blog posts.

**Details**
  - [x] [USER STORY:](https://github.com/users/Harmonica-Men/projects/10/views/2?pane=issue&itemId=70206168) Create models for comments linked to blog posts.
  - [x] [USER STORY: ](https://github.com/users/Harmonica-Men/projects/10/views/2?pane=issue&itemId=70206850)Create views and templates for adding and displaying comments.
  - [x] [USER STORY: ](https://github.com/users/Harmonica-Men/projects/10/views/1?pane=issue&itemId=70207750)Implement moderation features for comments (e.g., approval workflow).
