### ISSUE TITLE
EPIC 7 (Search and Filtering)

### ISSUE THREAD

**Issue by Harmonica-Men** [Harmonica-Men/AstroShare-Blog#12]
**Description:** Implement search and filtering capabilities.

**Details:**

  - [x] [USER STORY:](https://github.com/users/Harmonica-Men/projects/10/views/2?pane=issue&itemId=70212442) Add a search bar to allow users to search for posts.
  - [x] [USER STORY:](https://github.com/users/Harmonica-Men/projects/10/views/2?pane=issue&itemId=70212964) Implement filtering by categories, tags, and publication dates.
  - [x] [USER STORY:](https://github.com/users/Harmonica-Men/projects/10/views/2?pane=issue&itemId=70129504)  Optimize search and filter queries for performance.
