### ISSUE TITLE
EPIC 3 (User Authentication)

### ISSUE THREAD

**Issue by Harmonica-Men** [Harmonica-Men/AstroShare-Blog#8]
**Description:** Add user authentication to allow for author logins and secure post-management.

**Details:**

  - [x] [USER STORY:](https://github.com/users/Harmonica-Men/projects/10/views/1?pane=issue&itemId=70201797) Set up Django’s built-in authentication system.
  - [x] [USER STORY: ](https://github.com/users/Harmonica-Men/projects/10/views/1?pane=issue&itemId=70203518)Create registration, login, and logout views and templates.
  - [x] [USER STORY: ](https://github.com/users/Harmonica-Men/projects/10/views/1?pane=issue&itemId=70204403)Implement user-specific actions, such as creating, editing, and deleting blog posts.
